include: package:lint/analysis_options.yaml

linter:
  rules:
    join_return_with_assignment: false
    non_constant_identifier_names: false
    always_use_package_imports: false
    depend_on_referenced_packages: false
    sort_pub_dependencies: false