name: etiya_chatbot_flutter
description: A new Flutter project.
version: 0.0.2
repository: https://github.com/Etiya/etiya_chatbot_flutter.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.0.2

  equatable: ^2.0.3

  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1

  # https://pub.dev/packages/http
  http: ^0.13.4

  # https://pub.dev/packages/logger
  logger: ^1.1.0

  # https://pub.dev/packages/photo_view
  photo_view: ^0.13.0

  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.13

  # https://pub.dev/packages/socket_io_client
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

  # https://pub.dev/packages/swifty_chat
  swifty_chat: ^1.2.0

  togg_mobile_super_app_sdk:
    git:
      url: https://gitlab.togg.com.tr/digitalplatform/togg-mobile/mobile-super-app/togg_mobile_superapp_sdk
      ref: socket-client-proxy
#      ref: main

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.0.18

  # https://pub.dev/packages/uuid
  uuid: ^3.0.5

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  mockito: ^5.0.17
  test: ^1.17.0
#  mocktail: ^0.2.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
