name: etiya_chatbot_flutter
description: A new Flutter project.
version: 0.0.10
repository: https://github.com/Etiya/etiya_chatbot_flutter.git

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.0.3

  equatable: ^2.0.3

  etiya_chatbot_data:
    git:
      url: https://github.com/Etiya/etiya_chatbot_flutter
      path: packages/etiya_chatbot_core/etiya_chatbot_data
      ref: customer/togg
#    path: packages/etiya_chatbot_core/etiya_chatbot_data

  etiya_chatbot_domain:
    git:
      url: https://github.com/Etiya/etiya_chatbot_flutter
      path: packages/etiya_chatbot_core/etiya_chatbot_domain
      ref: customer/togg
#    path: packages/etiya_chatbot_core/etiya_chatbot_domain

  etiya_chatbot_mocked_data:
    git:
      url: https://github.com/Etiya/etiya_chatbot_flutter
      path: packages/etiya_chatbot_core/etiya_chatbot_mocked_data
      ref: customer/togg
#    path: packages/etiya_chatbot_core/etiya_chatbot_mocked_data

  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1

  # https://pub.dev/packages/flutter_rating_bar
  flutter_rating_bar: ^4.0.1

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^10.1.0

  # https://pub.dev/packages/logger
  logger: ^1.1.0

  # https://pub.dev/packages/photo_view
  photo_view: ^0.14.0

  # https://pub.dev/packages/swifty_chat
  swifty_chat: ^1.3.0

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.3

  # https://pub.dev/packages/uuid
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

  mockito: ^5.2.0
  mocktail: ^0.3.0

  styled_widget: ^0.4.0+3

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
