name: etiya_chatbot_flutter
description: A new Flutter project.
version: 0.1.1
repository: https://github.com/Etiya/etiya_chatbot_flutter.git
publish_to: none
environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:


 
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0
  #  swifty_chat_data: ^0.1.0
  # https://pub.dev/packages/swifty_chat


  togg_mobile_super_app_sdk:
    git:
      url: https://gitlab.togg.com.tr/digitalplatform/togg-mobile/mobile-super-app/togg_mobile_superapp_sdk
      ref: 4a7a975f859310c77430da5ecebd9da41922d4a3

 
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0

  flutter_bloc: ^8.0.1

  # https://pub.dev/packages/flutter_rating_bar
  flutter_rating_bar: ^4.0.1

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^10.1.0

  bloc: ^8.0.3

  equatable: ^2.0.3

  # https://pub.dev/packages/logger
  logger: ^1.1.0

  # https://pub.dev/packages/photo_view
  photo_view: ^0.14.0

  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.4

  # https://pub.dev/packages/uuid
  uuid: ^3.0.6

  flutter_hooks: ^0.18.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  show_up_animation: ^2.0.0
  flutter_html: ^2.2.1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  carousel_slider: ^4.1.1
  dart_extensions: ^2.2.0
  dcdg: ^4.1.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  mockito: ^5.2.0
  mocktail: ^0.3.0

  styled_widget: ^0.4.0+3
  swifty_chat_data: ^0.0.2


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true

