name: etiya_chatbot_data
description: Includes data models and domain repository implementations
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  etiya_chatbot_domain:
    git:
      url: https://github.com/Etiya/etiya_chatbot_flutter
      path: packages/etiya_chatbot_core/etiya_chatbot_domain
      ref: customer/togg-flutter-v2.10.5
#    path: ../etiya_chatbot_domain

  http: ^0.13.4
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0
#  swifty_chat_data: ^0.1.0
  # https://pub.dev/packages/swifty_chat
  swifty_chat: ^1.2.0

  togg_mobile_super_app_sdk:
    git:
      url: https://gitlab.togg.com.tr/digitalplatform/togg-mobile/mobile-super-app/togg_mobile_superapp_sdk
      ref: main

  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
