name: etiya_chatbot_data
description: Includes data models & domain repository implementations
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  etiya_chatbot_domain:
    path: ../etiya_chatbot_domain

  http: ^0.13.4
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  swifty_chat_data: ^0.0.2

  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
