name: etiya_chatbot_mocked_data
description: Mocked version of etiya_chatbot_data
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  etiya_chatbot_data:
    path: ../etiya_chatbot_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
