name: etiya_chatbot_domain
description: Includes domain layer abstraction (repositories)
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.21.3
