name: etiya_chatbot_domain
description: Includes domain layer abstraction (repositories)
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.21.3
